/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as OsdiTokenRouteImport } from './routes/osdi/$token'
import { Route as BookStatusRouteImport } from './routes/book/status'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPharmacyIndexRouteImport } from './routes/_authenticated/pharmacy/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedConsumablesIndexRouteImport } from './routes/_authenticated/consumables/index'
import { Route as AuthenticatedClinicalIndexRouteImport } from './routes/_authenticated/clinical/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedVisitsVisitIdRouteImport } from './routes/_authenticated/visits/$visitId'
import { Route as AuthenticatedPharmacySuppliersRouteImport } from './routes/_authenticated/pharmacy/suppliers'
import { Route as AuthenticatedPharmacyStockImportRouteImport } from './routes/_authenticated/pharmacy/stock-import'
import { Route as AuthenticatedPharmacyQueueRouteImport } from './routes/_authenticated/pharmacy/queue'
import { Route as AuthenticatedPharmacyOtcSalesRouteImport } from './routes/_authenticated/pharmacy/otc-sales'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminClinicSettingsRouteImport } from './routes/_authenticated/admin/clinic-settings'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const OsdiTokenRoute = OsdiTokenRouteImport.update({
  id: '/osdi/$token',
  path: '/osdi/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookStatusRoute = BookStatusRouteImport.update({
  id: '/book/status',
  path: '/book/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPharmacyIndexRoute =
  AuthenticatedPharmacyIndexRouteImport.update({
    id: '/pharmacy/',
    path: '/pharmacy/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsumablesIndexRoute =
  AuthenticatedConsumablesIndexRouteImport.update({
    id: '/consumables/',
    path: '/consumables/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClinicalIndexRoute =
  AuthenticatedClinicalIndexRouteImport.update({
    id: '/clinical/',
    path: '/clinical/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVisitsVisitIdRoute =
  AuthenticatedVisitsVisitIdRouteImport.update({
    id: '/visits/$visitId',
    path: '/visits/$visitId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacySuppliersRoute =
  AuthenticatedPharmacySuppliersRouteImport.update({
    id: '/pharmacy/suppliers',
    path: '/pharmacy/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyStockImportRoute =
  AuthenticatedPharmacyStockImportRouteImport.update({
    id: '/pharmacy/stock-import',
    path: '/pharmacy/stock-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyQueueRoute =
  AuthenticatedPharmacyQueueRouteImport.update({
    id: '/pharmacy/queue',
    path: '/pharmacy/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyOtcSalesRoute =
  AuthenticatedPharmacyOtcSalesRouteImport.update({
    id: '/pharmacy/otc-sales',
    path: '/pharmacy/otc-sales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminClinicSettingsRoute =
  AuthenticatedAdminClinicSettingsRouteImport.update({
    id: '/admin/clinic-settings',
    path: '/admin/clinic-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/book/status': typeof BookStatusRoute
  '/osdi/$token': typeof OsdiTokenRoute
  '/book/': typeof BookIndexRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/clinic-settings': typeof AuthenticatedAdminClinicSettingsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/pharmacy/otc-sales': typeof AuthenticatedPharmacyOtcSalesRoute
  '/pharmacy/queue': typeof AuthenticatedPharmacyQueueRoute
  '/pharmacy/stock-import': typeof AuthenticatedPharmacyStockImportRoute
  '/pharmacy/suppliers': typeof AuthenticatedPharmacySuppliersRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/clinical/': typeof AuthenticatedClinicalIndexRoute
  '/consumables/': typeof AuthenticatedConsumablesIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/book/status': typeof BookStatusRoute
  '/osdi/$token': typeof OsdiTokenRoute
  '/book': typeof BookIndexRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/clinic-settings': typeof AuthenticatedAdminClinicSettingsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/pharmacy/otc-sales': typeof AuthenticatedPharmacyOtcSalesRoute
  '/pharmacy/queue': typeof AuthenticatedPharmacyQueueRoute
  '/pharmacy/stock-import': typeof AuthenticatedPharmacyStockImportRoute
  '/pharmacy/suppliers': typeof AuthenticatedPharmacySuppliersRoute
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/clinical': typeof AuthenticatedClinicalIndexRoute
  '/consumables': typeof AuthenticatedConsumablesIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/pharmacy': typeof AuthenticatedPharmacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/book/status': typeof BookStatusRoute
  '/osdi/$token': typeof OsdiTokenRoute
  '/book/': typeof BookIndexRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/clinic-settings': typeof AuthenticatedAdminClinicSettingsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/pharmacy/otc-sales': typeof AuthenticatedPharmacyOtcSalesRoute
  '/_authenticated/pharmacy/queue': typeof AuthenticatedPharmacyQueueRoute
  '/_authenticated/pharmacy/stock-import': typeof AuthenticatedPharmacyStockImportRoute
  '/_authenticated/pharmacy/suppliers': typeof AuthenticatedPharmacySuppliersRoute
  '/_authenticated/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/clinical/': typeof AuthenticatedClinicalIndexRoute
  '/_authenticated/consumables/': typeof AuthenticatedConsumablesIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/book/status'
    | '/osdi/$token'
    | '/book/'
    | '/admin/audit-logs'
    | '/admin/clinic-settings'
    | '/admin/roles'
    | '/admin/users'
    | '/patients/$patientId'
    | '/pharmacy/otc-sales'
    | '/pharmacy/queue'
    | '/pharmacy/stock-import'
    | '/pharmacy/suppliers'
    | '/visits/$visitId'
    | '/appointments/'
    | '/clinical/'
    | '/consumables/'
    | '/patients/'
    | '/pharmacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/book/status'
    | '/osdi/$token'
    | '/book'
    | '/admin/audit-logs'
    | '/admin/clinic-settings'
    | '/admin/roles'
    | '/admin/users'
    | '/patients/$patientId'
    | '/pharmacy/otc-sales'
    | '/pharmacy/queue'
    | '/pharmacy/stock-import'
    | '/pharmacy/suppliers'
    | '/visits/$visitId'
    | '/appointments'
    | '/clinical'
    | '/consumables'
    | '/patients'
    | '/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/book/status'
    | '/osdi/$token'
    | '/book/'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/clinic-settings'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/users'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/pharmacy/otc-sales'
    | '/_authenticated/pharmacy/queue'
    | '/_authenticated/pharmacy/stock-import'
    | '/_authenticated/pharmacy/suppliers'
    | '/_authenticated/visits/$visitId'
    | '/_authenticated/appointments/'
    | '/_authenticated/clinical/'
    | '/_authenticated/consumables/'
    | '/_authenticated/patients/'
    | '/_authenticated/pharmacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  BookStatusRoute: typeof BookStatusRoute
  OsdiTokenRoute: typeof OsdiTokenRoute
  BookIndexRoute: typeof BookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osdi/$token': {
      id: '/osdi/$token'
      path: '/osdi/$token'
      fullPath: '/osdi/$token'
      preLoaderRoute: typeof OsdiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/status': {
      id: '/book/status'
      path: '/book/status'
      fullPath: '/book/status'
      preLoaderRoute: typeof BookStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/': {
      id: '/_authenticated/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AuthenticatedPharmacyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consumables/': {
      id: '/_authenticated/consumables/'
      path: '/consumables'
      fullPath: '/consumables/'
      preLoaderRoute: typeof AuthenticatedConsumablesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clinical/': {
      id: '/_authenticated/clinical/'
      path: '/clinical'
      fullPath: '/clinical/'
      preLoaderRoute: typeof AuthenticatedClinicalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visits/$visitId': {
      id: '/_authenticated/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/suppliers': {
      id: '/_authenticated/pharmacy/suppliers'
      path: '/pharmacy/suppliers'
      fullPath: '/pharmacy/suppliers'
      preLoaderRoute: typeof AuthenticatedPharmacySuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/stock-import': {
      id: '/_authenticated/pharmacy/stock-import'
      path: '/pharmacy/stock-import'
      fullPath: '/pharmacy/stock-import'
      preLoaderRoute: typeof AuthenticatedPharmacyStockImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/queue': {
      id: '/_authenticated/pharmacy/queue'
      path: '/pharmacy/queue'
      fullPath: '/pharmacy/queue'
      preLoaderRoute: typeof AuthenticatedPharmacyQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/otc-sales': {
      id: '/_authenticated/pharmacy/otc-sales'
      path: '/pharmacy/otc-sales'
      fullPath: '/pharmacy/otc-sales'
      preLoaderRoute: typeof AuthenticatedPharmacyOtcSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clinic-settings': {
      id: '/_authenticated/admin/clinic-settings'
      path: '/admin/clinic-settings'
      fullPath: '/admin/clinic-settings'
      preLoaderRoute: typeof AuthenticatedAdminClinicSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminClinicSettingsRoute: typeof AuthenticatedAdminClinicSettingsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPharmacyOtcSalesRoute: typeof AuthenticatedPharmacyOtcSalesRoute
  AuthenticatedPharmacyQueueRoute: typeof AuthenticatedPharmacyQueueRoute
  AuthenticatedPharmacyStockImportRoute: typeof AuthenticatedPharmacyStockImportRoute
  AuthenticatedPharmacySuppliersRoute: typeof AuthenticatedPharmacySuppliersRoute
  AuthenticatedVisitsVisitIdRoute: typeof AuthenticatedVisitsVisitIdRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedClinicalIndexRoute: typeof AuthenticatedClinicalIndexRoute
  AuthenticatedConsumablesIndexRoute: typeof AuthenticatedConsumablesIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedPharmacyIndexRoute: typeof AuthenticatedPharmacyIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminClinicSettingsRoute: AuthenticatedAdminClinicSettingsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPharmacyOtcSalesRoute: AuthenticatedPharmacyOtcSalesRoute,
  AuthenticatedPharmacyQueueRoute: AuthenticatedPharmacyQueueRoute,
  AuthenticatedPharmacyStockImportRoute: AuthenticatedPharmacyStockImportRoute,
  AuthenticatedPharmacySuppliersRoute: AuthenticatedPharmacySuppliersRoute,
  AuthenticatedVisitsVisitIdRoute: AuthenticatedVisitsVisitIdRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedClinicalIndexRoute: AuthenticatedClinicalIndexRoute,
  AuthenticatedConsumablesIndexRoute: AuthenticatedConsumablesIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedPharmacyIndexRoute: AuthenticatedPharmacyIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  BookStatusRoute: BookStatusRoute,
  OsdiTokenRoute: OsdiTokenRoute,
  BookIndexRoute: BookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
